name: check
on: [push]
jobs:
  shell-linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run linter for shell files
        run: shellcheck *.sh
  markdownlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check markdown files using `markdownlint`
        run: |
          sudo npm install -g markdownlint-cli
          markdownlint *.md
  update-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create some file for update check
        run: |
          touch /var/www/html/mediawiki/LocalSettings.php
          mkdir -pv /var/www/html/mediawiki/images/
          mkdir -pv /var/www/html/mediawiki/extensions/
          mkdir -pv /var/www/html/mediawiki/resources/assets/
      - name: Check that update script is not cause any errors
        run: |
          bash update.sh
